queue_rules:
  - name: dep-update
    batch_size: 100
    batch_max_wait_time: 30 min
    queue_conditions:
      - author = dependabot[bot]

pull_request_rules:
  - name: Automatic approve for Dependabot pull requests
    conditions:
      - author = dependabot[bot]
    actions:
      review:
        type: APPROVE

  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author = dependabot[bot]
      - "#approved-reviews-by>=1"
      - status-success=Test
    actions:
      queue:
        method: squash

  - name: Automatic approve for GitHub Actions pull requests
    conditions:
      - author = github-actions[bot]
    actions:
      review:
        type: APPROVE

  - name: Automatic merge for GitHub Actions pull requests
    conditions:
      - author = github-actions[bot]
      - "#approved-reviews-by>=1"
      - status-success=Test
    actions:
      merge:
        method: squash
