name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: read-all

jobs:
  build:
    name: Perform check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    if: github.repository == 'BarudakRosul/split-width'

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install package
        run: npm install

      - name: Testing code
        run: npm test
